In [1]:
# NUMPY OPERATIONS
print("Hello All")

Hello All


In [3]:
print("lets learn numpy")

lets learn numpy


In [7]:
import numpy as np
a=np.array([0,1,2,3,4,5])
print(a)
print(type(a))


[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
#1-D
#print dimensions
print(a.ndim)
#print number of rows and columns
print(a.shape)
#print length of array
len(a)

1
(6,)


6

In [10]:
#2-D
b=np.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [11]:
#2-D
#print dimensions
print(b.ndim)
#print number of rows and columns
print(b.shape)
#print length of array
len(b)

2
(2, 3)


2

In [12]:
#3-D
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [13]:
c.shape

(2, 2, 2)

In [14]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
#start,end(exclusive),step
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [16]:
#using linspace we can divide number range in given of parts
#start,end,number of parts
a=np.linspace(0,1,5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
#print 1 in 3 x 3 array
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#print 0 in 3 x 3 array
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#eye function returns all the diagonal elements same
#returns a 2d array with ones on diagonals and zeros elsewhere
c=np.eye(2)
c


array([[1., 0.],
       [0., 1.]])

In [20]:
#constructs a diagonal array
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
#extracts the diagonal elements in an array
np.diag(a)

array([1, 2, 3, 4])

In [22]:
#create array using random function
#create an array with given shape and populate random values
a=np.random.rand(3)
a

array([0.35270764, 0.03131002, 0.67607511])

In [23]:
#datatype of an array
a.dtype

dtype('float64')

In [24]:
a=np.arange(20)
a
a.dtype

dtype('int64')

In [25]:
#you can explicitly declare which datatype you want
a=np.arange(20,dtype='float64')
a


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [27]:
b=np.array([True,False,True,False])
print(b.dtype)

bool


In [28]:
#indexing and slicing
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
#starts from 5 till end
print(a[5:])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [30]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [31]:
#print array element of 2 row and 2 col
print(a[2,2])

3


In [32]:
#assigning value
a[1,1]=5
a

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 3]])

In [34]:
#assign 10 from 5 element till last element
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])